#!/bin/bash

volume="$(amixer get Master | tail -n1 | sed -r 's/.*\[(.*)%\].*/\1/')"

if [[ "$(amixer get Master | tail -n1 | rev | cut -c 2-3 | rev)" == 'on' ]];
	then
		vol=$volume'<'
	else
		vol=$volume'X'
fi
echo $vol
